
############################
# --- Required options --- #
############################

# Name of website
title: Wandering Mathematician

# Your name to show in the footer
author: Manuel Sedano Mendoza


theme: jekyll-theme-midnight
description: Blog about my errant learning on Statistics, and Data Science stuff.

navbar-links:
  About Me: "aboutme"



#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
#timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

#permalink: /:title/
lang: "en"
#excerp_sepatartor: "\n\n\n" #No idea what it does
date_format: "%B %d, %Y"

#Layout

show_social: true   #show site description and social links in the footer
show_excerpts: true   #show article excerpts on the home page
show_frame: true  #adds a gray frame to the site
show_sidebar: true #show a sidebar instead of the usual header

#Menu

navigation:
  - {file: "README.md", icon: address-card}
  - {title: "CV", ulr: "https://www.youtube.com/watch?v=V2cunxCGc_8&ab_channel=TRYBALS"}
  - {title: "Blog"}






###########################
# --- General options --- #
###########################

# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false


######################################
# --- Colours / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

